"""
    Module a
"""


def foo():
    """
        Prints message "Hello foo"
    """
    print("Hello foo")


# below docstring was generated by autodocstring extensions in vscode
def say_hello(name):
    """Prints Hello followed by the name
    
    Arguments:
        name {String} -- name of the person
    
    Returns:
        String -- Greeting message
    """
    print(f"Hello, {name}")
    return f"Hello, {name}"


if __name__ != "__main__":
    print("Importing module a")
